[project]
name = "flightpulse"
version = "0.1.0"
description = "Batch ELT pipeline for flight route analytics"
authors = [{name = "Ananya Gullapally"}]
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "duckdb",
    "pandas",
    "requests",
    "streamlit",
    "dbt-duckdb"
]

[tool.setuptools.packages.find]
include = ["ingestion*"]
exclude = ["data*", "dashboard*", "flightpulse_dbt*", "tests*"]

[project.optional-dependencies]
dev = [
    "pytest"
]
